version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/src
permissions:
   - object: /home/ec2-user/src
     pattern: "**"
     owner: ec2-user
     group: ec2-user
     mode: 755
     type:
       - file
hooks:
   AfterInstall:
    - location: scripts/djangostart.sh
      runas: root
