version: 0.0
os: linux
files:
   - source: /
     destination: /usr/local/src
permissions:
   - object: /usr/local/src
     pattern: "**"
     owner: ec2-user
     group: ec2-user
     mode: 755
     type:
       - file
