version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/src
permissions:
   - object: /home/ubuntu/src
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   AfterInstall:
    - location: scripts/djangostart.sh
      runas: root
