# Generated by Django 2.0 on 2018-08-02 14:24

from django.db import migrations, models
import django.db.models.deletion
import memorial_park_mgmnt_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=56)),
                ('first_name', models.CharField(max_length=56)),
                ('middle_name', models.CharField(blank=True, max_length=56, null=True)),
                ('birthdate', models.DateField()),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('house_number', models.CharField(blank=True, max_length=8, null=True)),
                ('street_name', models.CharField(blank=True, max_length=128, null=True)),
                ('barangay', models.CharField(max_length=128)),
                ('town', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('scanned_id', models.FileField(upload_to=memorial_park_mgmnt_app.models.scanned_id_directory_path)),
                ('other_address', models.CharField(blank=True, max_length=512, null=True)),
                ('business_name', models.CharField(blank=True, max_length=512, null=True)),
                ('business_address', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=56)),
                ('first_name', models.CharField(max_length=56)),
                ('middle_name', models.CharField(blank=True, max_length=56, null=True)),
                ('birthdate', models.DateField()),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('house_number', models.CharField(blank=True, max_length=8, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('barangay', models.CharField(max_length=128)),
                ('town', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('scanned_id', models.FileField(upload_to=memorial_park_mgmnt_app.models.scanned_id_directory_path)),
                ('other_address', models.CharField(blank=True, max_length=512, null=True)),
                ('business_name', models.CharField(blank=True, max_length=512, null=True)),
                ('business_address', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=32)),
                ('lot', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='memorial_park_mgmnt_app.Branch')),
            ],
        ),
    ]
